package com.mdu.DrawLine;

import com.jhlabs.image.*;

public class Filter {
  
  static String NULL = "null";
  
static Filter [] filters = {
new Filter(SparkleFilter.class, null),
new Filter(GrayFilter.class, null),
new Filter(DeinterlaceFilter.class, null),
new Filter(ContrastFilter.class, null),
new Filter(KeyFilter.class, null),
new Filter(HighPassFilter.class, null),
new Filter(AverageFilter.class, null),
new Filter(DisplaceFilter.class, null),
new Filter(WoodFilter.class, null),
new Filter(ShadowFilter.class, null),
new Filter(InterpolateFilter.class, null),
new Filter(ContourFilter.class, null),
new Filter(MapColorsFilter.class, null),
new Filter(ChromeFilter.class, null),
new Filter(MaskFilter.class, null),
new Filter(LightFilter.class, null),
new Filter(BorderFilter.class, null),
new Filter(WarpFilter.class, null),
new Filter(ShadeFilter.class, null),
new Filter(ScratchFilter.class, null),
new Filter(GlowFilter.class, null),
new Filter(TextureFilter.class, null),
new Filter(MapFilter.class, null),
new Filter(ScaleFilter.class, null),
new Filter(OilFilter.class, null),
new Filter(MotionBlurFilter.class, null),
new Filter(InvertAlphaFilter.class, null),
new Filter(SaturationFilter.class, null),
new Filter(SwizzleFilter.class, null),
new Filter(BlockFilter.class, null),
new Filter(CellularFilter.class, null),
new Filter(HalftoneFilter.class, null),
new Filter(BoxBlurFilter.class, new Object[] {
    "setHRadius", 5, 
    "setVRadius", 5, 
    "setIterations", 5
}),
new Filter(BumpFilter.class, null),
new Filter(BicubicScaleFilter.class, null),
new Filter(BrushedMetalFilter.class, null),
new Filter(GradientWipeFilter.class, null),
new Filter(QuantizeFilter.class, null),
new Filter(GaussianFilter.class, null),
new Filter(GlintFilter.class, null),
new Filter(EmbossFilter.class, null),
new Filter(ReduceNoiseFilter.class, null),
new Filter(LookupFilter.class, null),
new Filter(OutlineFilter.class, null),
new Filter(OffsetFilter.class, null),
new Filter(TileImageFilter.class, null),
new Filter(MarbleTexFilter.class, null),
new Filter(WaterFilter.class, null),
new Filter(PosterizeFilter.class, null),
new Filter(CausticsFilter.class, null),
new Filter(GainFilter.class, null),
new Filter(ShearFilter.class, null),
new Filter(GradientFilter.class, null),
new Filter(TwirlFilter.class, null),
new Filter(GrayscaleFilter.class, null),
new Filter(DissolveFilter.class, null),
new Filter(CropFilter.class, null),
new Filter(CurvesFilter.class, null),
new Filter(FeedbackFilter.class, null),
new Filter(FillFilter.class, null),
new Filter(DilateFilter.class, null),
new Filter(SolarizeFilter.class, null),
new Filter(JavaLnFFilter.class, null),
new Filter(UnsharpFilter.class, null),
new Filter(EdgeFilter.class, null),
new Filter(CompositeFilter.class, null),
new Filter(MaximumFilter.class, null),
new Filter(CheckFilter.class, null),
new Filter(GammaFilter.class, null),
new Filter(HSBAdjustFilter.class, null),
new Filter(SmearFilter.class, null),
new Filter(UnpremultiplyFilter.class, null),
new Filter(ShatterFilter.class, null),
new Filter(LevelsFilter.class, null),
new Filter(PointillizeFilter.class, null),
new Filter(OpacityFilter.class, null),
new Filter(ExposureFilter.class, null),
new Filter(Flush3DFilter.class, null),
new Filter(FieldWarpFilter.class, null),
new Filter(StampFilter.class, null),
new Filter(MarbleFilter.class, null),
new Filter(RenderTextFilter.class, null),
new Filter(WeaveFilter.class, null),
new Filter(PlasmaFilter.class, null),
new Filter(ErodeFilter.class, null),
new Filter(PerspectiveFilter.class, null),
new Filter(CrystallizeFilter.class, null),
new Filter(PolarFilter.class, null),
new Filter(DespeckleFilter.class, null),
new Filter(LaplaceFilter.class, null),
new Filter(QuiltFilter.class, null),
new Filter(DiffusionFilter.class, null),
new Filter(SmartBlurFilter.class, null),
new Filter(SphereFilter.class, null),
new Filter(DiffuseFilter.class, null),
new Filter(RotateFilter.class, null),
new Filter(EqualizeFilter.class, null),
new Filter(CircleFilter.class, null),
new Filter(RippleFilter.class, null),
new Filter(ChromaKeyFilter.class, null),
new Filter(RaysFilter.class, null),
new Filter(ShapeFilter.class, null),
new Filter(PinchFilter.class, null),
new Filter(ImageCombiningFilter.class, null),
new Filter(FlareFilter.class, null),
new Filter(ErodeAlphaFilter.class, null),
new Filter(BlurFilter.class, null),
new Filter(ThresholdFilter.class, null),
new Filter(ConvolveFilter.class, null),
new Filter(NoiseFilter.class, null),
new Filter(SharpenFilter.class, null),
new Filter(ApplyMaskFilter.class, null),
new Filter(SwimFilter.class, null),
new Filter(MinimumFilter.class, null),
new Filter(LensBlurFilter.class, null),
new Filter(FadeFilter.class, null),
new Filter(ChannelMixFilter.class, null),
new Filter(RGBAdjustFilter.class, null),
new Filter(DitherFilter.class, null),
new Filter(CurlFilter.class, null),
new Filter(ShineFilter.class, null),
new Filter(ColorHalftoneFilter.class, null),
new Filter(MirrorFilter.class, null),
new Filter(FBMFilter.class, null),
new Filter(PremultiplyFilter.class, null),
new Filter(FourColorFilter.class, null),
new Filter(MedianFilter.class, null),
new Filter(RescaleFilter.class, null),
new Filter(TritoneFilter.class, null),
new Filter(SkyFilter.class, null),
new Filter(FlipFilter.class, null),
new Filter(DoGFilter.class, null),
new Filter(KaleidoscopeFilter.class, null),
new Filter(LifeFilter.class, null),
new Filter(SkeletonFilter.class, null),
new Filter(VariableBlurFilter.class, null),
new Filter(InvertFilter.class, null)
  };
  
    Class<?> cls;
    Object[] params;
    
    public Filter(Class<?> cls,  Object[] param) {
      this.cls = cls;
      this.params = param;
    }
    
}
